//! Emits the cross-language test vector the Solidity side checks itself against.
//!
//! `bridge.md` §2a specifies the attestation preimage twice: once in Rust, in
//! `primitives::attest`, and once in Solidity, as an `abi.encodePacked` that a
//! contract has to reconstruct byte for byte before `ecrecover` can mean
//! anything. Two independent implementations of one byte layout is exactly the
//! shape of bug that passes every test on each side and fails only when the two
//! meet — and it would surface on-chain as attestations that recover to the
//! wrong address, which looks identical to workers being dishonest.
//!
//! So the layout is pinned by a vector rather than by agreement between two
//! prose descriptions. This example is the producer; `bridge/test/
//! AttestationVector.t.sol` is the consumer, and it asserts on the preimage,
//! the digest, and that `ecrecover` returns this signer.
//!
//! Deterministic on purpose — the key comes from `WorkerKey::derive`, not from
//! randomness — so re-running it produces the same file and a diff means a
//! layout change rather than noise.
//!
//! Regenerate with:
//!
//! ```text
//! cargo run --release -p primitives --example attestation_vector \
//!     > bridge/test/vectors/attestation.json
//! ```

use primitives::attest::{Claim, WorkerKey, hex_address};
use primitives::bytecode;

fn hex_bytes(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(2 + bytes.len() * 2);
    out.push_str("0x");
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

fn main() {
    // A label rather than a random key, so this file is reproducible. The
    // vector proves a layout, not a secret: publishing the signature of a
    // known-derived key over a fixed claim gives an attacker nothing they could
    // not compute themselves.
    let key = WorkerKey::derive("vector");

    // Values chosen to be unmistakable in a hex dump if a field is transposed:
    // the job id is not 0 or 1, and the two hashes differ in every byte.
    let job_id = 0x0102_0304_0506_0708;
    let bytecode_hash = bytecode::hash_bytecode(b"disca attestation vector bytecode");
    let result_hash = bytecode::hash_bytecode(b"disca attestation vector result");

    let claim = Claim::Result {
        job_id,
        bytecode_hash,
        result_hash,
    };
    let attestation = key.attest(&claim);

    println!("{{");
    println!(
        "  \"_comment\": \"Generated by primitives/examples/attestation_vector.rs. Do not hand-edit; regenerate.\","
    );
    println!("  \"domain\": \"DISCA/attest/result/v1\",");
    println!("  \"jobId\": {job_id},");
    println!("  \"bytecodeHash\": \"{}\",", hex_bytes(&bytecode_hash));
    println!("  \"resultHash\": \"{}\",", hex_bytes(&result_hash));
    println!("  \"preimage\": \"{}\",", hex_bytes(&claim.preimage()));
    println!("  \"digest\": \"{}\",", hex_bytes(&claim.digest()));
    println!("  \"signer\": \"{}\",", hex_address(&key.address()));
    println!("  \"r\": \"{}\",", hex_bytes(&attestation.r));
    println!("  \"s\": \"{}\",", hex_bytes(&attestation.s));
    println!("  \"v\": {}", attestation.v);
    println!("}}");
}
