[package]
name = "node"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true

[dependencies]
tfhe = { workspace = true }
primitives = { path = "../primitives" }
clap = { workspace = true, features = ["derive"] }
wincode = { workspace = true }
rayon = { workspace = true }
tiny_http = { workspace = true }
ureq = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
