// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {console2} from "forge-std/console2.sol";
import {DiscaBridge} from "../src/DiscaBridge.sol";

/// @notice The cross-language check: this contract's attestation digest against
/// bytes produced by `primitives/src/attest.rs`.
///
/// @dev Everything else in this suite tests Solidity against Solidity. That is
/// worth exactly nothing for the one property that actually has to hold, which
/// is that `DiscaBridge.attestationDigest` and `Claim::digest` are the same
/// function written twice in two languages (`docs/bridge.md` §2a). A divergence
/// there does not look like a bug: `ecrecover` still returns an address, just
/// not the signer's, so every honest worker in the network appears to be
/// signing badly and no job ever settles. Both sides would pass their own tests
/// the whole time.
///
/// The vector is generated by the Rust implementation and committed at
/// `test/vectors/attestation.json`. If it is not there yet this suite skips
/// rather than fails, so it starts checking the moment the file lands — but a
/// skip is not a pass, and the log line says so.
///
/// The assertions below were run green against a vector built with `cast
/// keccak` and `cast wallet sign` over the same 94-byte preimage, so a skip
/// here means the input is missing, not that the checks are untried. That is
/// evidence about foundry's EIP-191 and secp256k1, not about
/// `primitives/src/attest.rs`, which is the whole reason this file waits for
/// the real vector rather than shipping a locally generated one.
contract AttestationVectorTest is Test {
    using stdJson for string;

    string internal constant VECTOR_PATH = "./test/vectors/attestation.json";

    DiscaBridge internal bridge;

    function setUp() public {
        bridge = new DiscaBridge(1 hours);
    }

    function test_theSolidityDigestMatchesTheRustVector() public {
        if (!vm.exists(VECTOR_PATH)) {
            console2.log("SKIPPED: no cross-language vector at", VECTOR_PATH);
            console2.log("  Solidity has NOT been checked against primitives/src/attest.rs.");
            vm.skip(true);
            return;
        }

        string memory vector = vm.readFile(VECTOR_PATH);

        // The domain tag is part of the wire format, not an implementation
        // detail: `docs/bridge.md` §2a pairs it with a `/v1` suffix precisely so
        // that a future EIP-712 migration cannot be mistaken for this one.
        assertEq(
            vector.readString(".domain"),
            "DISCA/attest/result/v1",
            "the vector is for a different claim domain"
        );

        uint64 jobId = uint64(vector.readUint(".jobId"));
        bytes32 bytecodeHash = vector.readBytes32(".bytecodeHash");
        bytes32 resultHash = vector.readBytes32(".resultHash");

        // Preimage before digest. A mismatch in the 94-byte layout and a
        // mismatch in the EIP-191 prefix are different bugs, and comparing only
        // the digest cannot tell them apart.
        bytes memory preimage = bridge.attestationPreimage(jobId, bytecodeHash, resultHash);
        assertEq(preimage.length, 94, "the preimage is fixed at 94 bytes");
        assertEq(preimage, vector.readBytes(".preimage"), "preimage layout diverged from Rust");

        bytes32 digest = bridge.attestationDigest(jobId, bytecodeHash, resultHash);
        assertEq(digest, vector.readBytes32(".digest"), "digest construction diverged from Rust");

        // And the signature over it recovers the address Rust says signed —
        // which is the end-to-end statement: a signature produced by
        // `WorkerKey::attest` is one `fulfillJob` will count.
        address recovered = ecrecover(
            digest, uint8(vector.readUint(".v")), vector.readBytes32(".r"), vector.readBytes32(".s")
        );
        assertEq(recovered, vector.readAddress(".signer"), "ecrecover disagreed with k256");
        assertTrue(recovered != address(0), "ecrecover reports failure by returning zero");
    }
}
